name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build

    - name: Deploy to Server
      env:
        HOST: ${{ secrets.SERVER_HOST }}
        USERNAME: ${{ secrets.SERVER_USER }}
        SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
        TARGET_DIR: /var/www/demo
      run: |
        echo "$SSH_KEY" > ssh_key
        chmod 600 ssh_key
        rsync -avz -e "ssh -i ssh_key -o StrictHostKeyChecking=no" dist/ $USERNAME@$HOST:$TARGET_DIR
        ssh -i ssh_key -o StrictHostKeyChecking=no $USERNAME@$HOST "sudo systemctl restart nginx"
